-- Generated by tools/yml_to_lua.py from leaders.yml
starting_pieces = starting_pieces or {}

-- Kaiju
starting_pieces["Kaiju"] = {
  A = {
    building = "city",
    ships = 4
  },
  B = {
    building = "city",
    ships = 4
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Material"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Shapeshifter
starting_pieces["Shapeshifter"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Psionic", "Material"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Sentient
starting_pieces["Sentient"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "None",
    ships = 2
  },
  C = {
    building = "None",
    ships = 3
  },
  resources = {"Material", "Psionic"},
  D = {
    building = "None",
    ships = 3
  }
}

-- Hierarch
starting_pieces["Hierarch"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Relic", "Material"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Smuggler
starting_pieces["Smuggler"] = {
  A = {
    building = "starport",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Fuel", "Weapon"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Manipulator
starting_pieces["Manipulator"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Psionic", "Psionic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Necromancer
starting_pieces["Necromancer"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Psionic", "Weapon"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Composer
starting_pieces["Composer"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 3
  },
  resources = {"Material", "Weapon"},
  D = {
    building = "None",
    ships = 3
  }
}

-- Maw
starting_pieces["Maw"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Material"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Saint
starting_pieces["Saint"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "city",
    ships = 3
  },
  C = {
    building = "None",
    ships = 3
  },
  resources = {"Psionic", "Relic"},
  D = {
    building = "None",
    ships = 3
  }
}

-- Seer
starting_pieces["Seer"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Psionic", "Psionic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Terrestrial
starting_pieces["Terrestrial"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "city",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Material", "Relic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- General
starting_pieces["General"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Weapon"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Sentinel
starting_pieces["Sentinel"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Material", "Weapon"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Prefect
starting_pieces["Prefect"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Relic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Ghost
starting_pieces["Ghost"] = {
  A = {
    building = "starport",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Fuel", "Psionic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Chosen
starting_pieces["Chosen"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Relic", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Sage
starting_pieces["Sage"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Relic", "Relic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Gambler
starting_pieces["Gambler"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Psionic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Engineer
starting_pieces["Engineer"] = {
  A = {
    building = "starport",
    ships = 3
  },
  B = {
    building = "city",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Material", "Material"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Magician
starting_pieces["Magician"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "city",
    ships = 3
  },
  C = {
    building = "None",
    ships = 3
  },
  resources = {"Psionic", "Material"},
  D = {
    building = "None",
    ships = 3
  }
}

-- Weaver
starting_pieces["Weaver"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Relic", "Material"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Dreamer
starting_pieces["Dreamer"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Psionic", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Seeker
starting_pieces["Seeker"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "city",
    ships = 3
  },
  C = {
    building = "None",
    ships = 3
  },
  resources = {"Material", "Relic"},
  D = {
    building = "None",
    ships = 3
  }
}

-- Augur
starting_pieces["Augur"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Psionic", "Relic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Alchemist
starting_pieces["Alchemist"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Psionic", "Relic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Architect
starting_pieces["Architect"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Relic", "Material"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Martyr
starting_pieces["Martyr"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "city",
    ships = 3
  },
  C = {
    building = "None",
    ships = 3
  },
  resources = {"Psionic", "Fuel"},
  D = {
    building = "None",
    ships = 3
  }
}

-- Scourge
starting_pieces["Scourge"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Beggar
starting_pieces["Beggar"] = {
  A = {
    building = "starport",
    ships = 3
  },
  B = {
    building = "None",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"None", "None"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Feral
starting_pieces["Feral"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Conduit
starting_pieces["Conduit"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Psionic", "Material"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Puppeteer
starting_pieces["Puppeteer"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Psionic", "Relic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Automaton
starting_pieces["Automaton"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Material", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Golem
starting_pieces["Golem"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Material", "Weapon"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Solian
starting_pieces["Solian"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Relic", "Material"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Racketeer
starting_pieces["Racketeer"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Relic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Terraformer
starting_pieces["Terraformer"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Psionic", "Material"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Trickster
starting_pieces["Trickster"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Psionic", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Nomad
starting_pieces["Nomad"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 3
  },
  resources = {"Material", "Fuel"},
  D = {
    building = "None",
    ships = 3
  }
}

-- Iconoclast
starting_pieces["Iconoclast"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "city",
    ships = 3
  },
  C = {
    building = "None",
    ships = 3
  },
  resources = {"Psionic", "Weapon"},
  D = {
    building = "None",
    ships = 3
  }
}

-- Fiend
starting_pieces["Fiend"] = {
  A = {
    building = "None",
    ships = 3
  },
  B = {
    building = "None",
    ships = 3
  },
  C = {
    building = "None",
    ships = 3
  },
  resources = {"None", "None"},
  D = {
    building = "None",
    ships = 3
  }
}

-- Hustler
starting_pieces["Hustler"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Relic", "Relic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Curator
starting_pieces["Curator"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Psionic", "Relic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Cartographer
starting_pieces["Cartographer"] = {
  A = {
    building = "starport",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 3
  },
  resources = {"Fuel", "Relic"},
  D = {
    building = "None",
    ships = 3
  }
}

-- Custodian
starting_pieces["Custodian"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 3
  },
  resources = {"Relic", "Fuel"},
  D = {
    building = "None",
    ships = 3
  }
}

-- Salvager
starting_pieces["Salvager"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Relic", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Chief
starting_pieces["Chief"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Relic", "Weapon"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Duelist
starting_pieces["Duelist"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Relic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Prophet
starting_pieces["Prophet"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 3
  },
  resources = {"Psionic", "Material"},
  D = {
    building = "None",
    ships = 3
  }
}

-- Broker
starting_pieces["Broker"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Material", "Psionic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Siegebreaker
starting_pieces["Siegebreaker"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Courier
starting_pieces["Courier"] = {
  A = {
    building = "starport",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Fuel", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Forager
starting_pieces["Forager"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Relic", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Punter
starting_pieces["Punter"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 3
  },
  resources = {"Weapon", "Fuel"},
  D = {
    building = "None",
    ships = 3
  }
}

-- Insurgent
starting_pieces["Insurgent"] = {
  A = {
    building = "starport",
    ships = 3
  },
  B = {
    building = "None",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Relic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Bomber
starting_pieces["Bomber"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Musician
starting_pieces["Musician"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Material", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Ozymandias
starting_pieces["Ozymandias"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 3
  },
  resources = {"Fuel", "Relic"},
  D = {
    building = "None",
    ships = 3
  }
}

-- Collector
starting_pieces["Collector"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Relic", "Relic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Samurai
starting_pieces["Samurai"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Relic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Assassin
starting_pieces["Assassin"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Psionic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Witch
starting_pieces["Witch"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Psionic", "Relic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Ambassador
starting_pieces["Ambassador"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Psionic", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Shaman
starting_pieces["Shaman"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Material", "Psionic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Mediator
starting_pieces["Mediator"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Psionic", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Despot
starting_pieces["Despot"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Fuel", "Relic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Viceroy
starting_pieces["Viceroy"] = {
  A = {
    building = "starport",
    ships = 3
  },
  B = {
    building = "None",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Relic", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Artificer
starting_pieces["Artificer"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Material", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Warmonger
starting_pieces["Warmonger"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Weapon"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Extortioner
starting_pieces["Extortioner"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 3
  },
  resources = {"Psionic", "Weapon"},
  D = {
    building = "None",
    ships = 3
  }
}

-- Emperor
starting_pieces["Emperor"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 3
  },
  resources = {"Weapon", "Material"},
  D = {
    building = "None",
    ships = 3
  }
}

-- Titan
starting_pieces["Titan"] = {
  A = {
    building = "city",
    ships = 4
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Relic", "Weapon"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Egoist
starting_pieces["Egoist"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Psionic", "Material"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Enforcer
starting_pieces["Enforcer"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Relic", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Treasurer
starting_pieces["Treasurer"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "city",
    ships = 3
  },
  C = {
    building = "None",
    ships = 3
  },
  resources = {"Material", "Material"},
  D = {
    building = "None",
    ships = 3
  }
}

-- Wayfinder
starting_pieces["Wayfinder"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "city",
    ships = 4
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Psionic", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Champion
starting_pieces["Champion"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 3
  },
  resources = {"Relic", "Weapon"},
  D = {
    building = "None",
    ships = 3
  }
}

-- Tribune
starting_pieces["Tribune"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 3
  },
  resources = {"Relic", "Weapon"},
  D = {
    building = "None",
    ships = 3
  }
}

-- Dissector
starting_pieces["Dissector"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Relic", "Material"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Schemer
starting_pieces["Schemer"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Psionic", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Hydra
starting_pieces["Hydra"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 3
  },
  resources = {"Weapon", "Material"},
  D = {
    building = "None",
    ships = 3
  }
}

-- Enchanter
starting_pieces["Enchanter"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Psionic", "Relic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Creator
starting_pieces["Creator"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Material", "Relic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Messiah
starting_pieces["Messiah"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Material"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Abomination
starting_pieces["Abomination"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Psionic", "Weapon"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Crusader
starting_pieces["Crusader"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Relic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Phantom
starting_pieces["Phantom"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Fuel", "Weapon"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Harbormaster
starting_pieces["Harbormaster"] = {
  A = {
    building = "starport",
    ships = 3
  },
  B = {
    building = "None",
    ships = 3
  },
  C = {
    building = "None",
    ships = 3
  },
  resources = {"Material", "Fuel"},
  D = {
    building = "None",
    ships = 3
  }
}

-- Investor
starting_pieces["Investor"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"None", "None"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Envoy
starting_pieces["Envoy"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Fuel", "Psionic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Syndic
starting_pieces["Syndic"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "None",
    ships = 3
  },
  C = {
    building = "None",
    ships = 3
  },
  resources = {"Psionic", "Material"},
  D = {
    building = "None",
    ships = 3
  }
}

-- Solicitor
starting_pieces["Solicitor"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Relic", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Seraph
starting_pieces["Seraph"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 3
  },
  resources = {"Fuel", "Relic"},
  D = {
    building = "None",
    ships = 3
  }
}

-- Paragon
starting_pieces["Paragon"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Psionic", "Relic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Tactician
starting_pieces["Tactician"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Material"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Purist
starting_pieces["Purist"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Psionic", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Marauder
starting_pieces["Marauder"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Berserker
starting_pieces["Berserker"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Underwriter
starting_pieces["Underwriter"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Material", "Weapon"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Doppelganger
starting_pieces["Doppelganger"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Psionic", "Weapon"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Bulwark
starting_pieces["Bulwark"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 3
  },
  resources = {"Psionic", "Weapon"},
  D = {
    building = "None",
    ships = 3
  }
}

-- Demon
starting_pieces["Demon"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "city",
    ships = 3
  },
  C = {
    building = "None",
    ships = 3
  },
  resources = {"Weapon", "Material"},
  D = {
    building = "None",
    ships = 3
  }
}

-- Soulbinder
starting_pieces["Soulbinder"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Psionic", "Weapon"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Vessel
starting_pieces["Vessel"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Psionic", "Weapon"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Conqueror
starting_pieces["Conqueror"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Weapon"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Comedian
starting_pieces["Comedian"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Psionic", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Animator
starting_pieces["Animator"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Material", "Psionic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Merchant
starting_pieces["Merchant"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Material", "Relic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Wretch
starting_pieces["Wretch"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Relic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Rascal
starting_pieces["Rascal"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Fuel", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Devourer
starting_pieces["Devourer"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Fuel", "Weapon"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Swarm
starting_pieces["Swarm"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 3
  },
  resources = {"Material", "Psionic"},
  D = {
    building = "None",
    ships = 3
  }
}

-- Predator
starting_pieces["Predator"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Material"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Reaver
starting_pieces["Reaver"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Psionic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Prospector
starting_pieces["Prospector"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Relic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Smokecaller
starting_pieces["Smokecaller"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Fuel", "Psionic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Dragon
starting_pieces["Dragon"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Psionic", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Sniper
starting_pieces["Sniper"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Poltergeist
starting_pieces["Poltergeist"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Psionic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Homesteader
starting_pieces["Homesteader"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 3
  },
  resources = {"Material", "Fuel"},
  D = {
    building = "None",
    ships = 3
  }
}

-- Instigator
starting_pieces["Instigator"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Relic", "Weapon"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Replicator
starting_pieces["Replicator"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Material", "Psionic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Armsdealer
starting_pieces["Armsdealer"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Material"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Veteran
starting_pieces["Veteran"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Evader
starting_pieces["Evader"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Fuel", "Psionic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Mathematician
starting_pieces["Mathematician"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Relic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Underdog
starting_pieces["Underdog"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Material", "Psionic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Mobster
starting_pieces["Mobster"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Relic", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Glutton
starting_pieces["Glutton"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Psionic", "Material"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Contrarian
starting_pieces["Contrarian"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Relic", "Weapon"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Cat
starting_pieces["Cat"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Psionic", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Cavalier
starting_pieces["Cavalier"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Relic", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Surveyor
starting_pieces["Surveyor"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Material", "Relic"},
  D = {
    building = "None",
    ships = 2
  }
}

-- Jester
starting_pieces["Jester"] = {
  A = {
    building = "city",
    ships = 3
  },
  B = {
    building = "starport",
    ships = 3
  },
  C = {
    building = "None",
    ships = 2
  },
  resources = {"Weapon", "Fuel"},
  D = {
    building = "None",
    ships = 2
  }
}
